os: linux
language: shell
install:
  - wget https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz
  - tar -xzvf mdbook-*.tar.gz
script:
  ./mdbook build
deploy:
  edge: true # use Travis-CI dpl v2
  provider: pages
  local_dir: book
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: travis-demo # Will default to master branch if on.branch is removed
